### ISSUE TITLE
Enable multiple values for the inLanguage property

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/credentialPublisher#11]
See https://github.com/CredentialEngine/vocabularies/issues/506#issuecomment-359535413

- Update the registry validation schema to allow multiple values for the `inLanguage` property
- Update the publisher to allow multiple values for the `inLanguage` property
- Update the finder to handle multiple values for the `inLanguage` property

**Comment by cwd-mparsons** [comment]
We have enabled multiple values for inLanguage in the API and registry.
