### ISSUE TITLE
Make ceterms:inLanguage a required field

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/credentialPublisher#12]
Per an internal discussion on 3/1/2018:
It seems like it would be a good practice to require the inLanguage property.

**Comment by stuartasutton** [comment]
I think that you'd have difficulty requiring it. Most conventional applications (from which data wold be mapped) don't identify the language of a document because it seems contextually unnecessary to them (e.g., 'everything we do is in English and our users speak English').

**Comment by stuartasutton** [comment]
Unless complicated by signatures (he sigh), the registry could assume a default of "en-US" for `inLanguage` (as well as `langString` properties) and supply the value if the submitter does not. Of course, the option should be available to manually over-ride the default.

**Comment by cwd-mparsons** [comment]
Closing, as inLanguage is now required.
