### ISSUE TITLE
CE package URI does not resolve

### ISSUE THREAD

**Issue by brandonopened** [CredentialEngine/credentialPublisher#14]
https://credentialengineregistry.org/resources/ce-f6e25e8a-6a93-11e8-98be-0242ac120003

Hi, I have loaded a CASE framework into the competency manager and am unable to:
1) Exporot a full CF Package.. just document or items? https://cass.credentialengine.org/api/ims/case/v1p0/CFDocuments/97c398d5e09d30b00f8bf9e8786fcc0c

2) Retrieve the derivative framework URL: https://credentialengineregistry.org/resources/ce-f6e25e8a-6a93-11e8-98be-0242ac120003 .  (this should show the full CASE CF Package referenced at frameworks.act.org/uri/f6e25e8a-6a93-11e8-98be-0242ac120003

If this is a CASS bug I should file instead, please let me know.

**Comment by jkitchensSIUC** [comment]
@Lomilar @woodkri please move this to https://github.com/cassproject/cass-editor/issues/634

@brandonopened we manage a CASS repo so this will be moved to it and we'll respond to you via this issue in that repo.
